### ISSUE TITLE
Misspelled "positive"

### ISSUE THREAD

**Issue by LouisWhite15** [Bencargs/Market-Analysis#2]
**Describe the bug**
Just a simple typo on the word "positive" in the ConfusionCategory enum

Problematic code here:
https://github.com/Bencargs/Market-Analysis/blob/ba616de63f5c35d9a643e3af4338e9421c2a504a/MarketAnalysis/Models/ConfusionCategory.cs#L5

**Comment by Bencargs** [comment]
Fixed
