### ISSUE TITLE
Tests required

### ISSUE THREAD

**Issue by LouisWhite15** [Bencargs/Market-Analysis#3]
**Describe the bug**
No tests

**To Reproduce**
1. Go to the repo
2. Click on MarketAnalysisTests
3. Scroll down to the no tests
4. See error - No tests

**Expected behavior**
Tests

**Screenshots**
![image](https://user-images.githubusercontent.com/12193721/74906916-4482d180-53ed-11ea-8789-27c75e9891ab.png)

**Additional content**
Hey champ, how about these tests ey?

**Comment by Bencargs** [comment]
Tests added
